name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ ØªÙ… ØªØ´ØºÙŠÙ„ Ø§Ù„Ù…Ù‡Ù…Ø© ØªÙ„Ù‚Ø§Ø¦ÙŠÙ‹Ø§ Ø¨ÙˆØ§Ø³Ø·Ø© Ø­Ø¯Ø« ${{ github.event_name }} event."
      - run: echo "ğŸ§ ÙŠØªÙ… ØªØ´ØºÙŠÙ„ Ù‡Ø°Ù‡ Ø§Ù„Ù…Ù‡Ù…Ø© Ø§Ù„Ø¢Ù† Ø¹Ù„Ù‰ Ø®Ø§Ø¯Ù… ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” Ø§Ø³Ù… ÙØ±Ø¹Ùƒ Ù‡Ùˆ ${{ github.ref }} ÙˆÙ…Ø³ØªÙˆØ¯Ø¹Ùƒ Ù‡Ùˆ ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ ØªÙ… Ø§Ø³ØªÙ†Ø³Ø§Ø® Ù…Ø³ØªÙˆØ¯Ø¹ ${{ github.repository }} Ø¥Ù„Ù‰ Ø¬Ù‡Ø§Ø² Ø§Ù„ØªØ´ØºÙŠÙ„.."
      - run: echo "ğŸ–¥ï¸ Ø³ÙŠØ± Ø§Ù„Ø¹Ù…Ù„ Ø¬Ø§Ù‡Ø² Ø§Ù„Ø¢Ù† Ù„Ø§Ø®ØªØ¨Ø§Ø± Ø§Ù„ÙƒÙˆØ¯ Ø¹Ù„Ù‰ Ø¬Ù‡Ø§Ø² Ø§Ù„ØªØ´ØºÙŠÙ„."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ Ø­Ø§Ù„Ø© Ø§Ù„Ù…Ù‡Ù…Ø© Ù‡ÙŠ ${{ job.status }}."
